// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_aoc_day_phase_ from "./routes/api/aoc/[day]/[phase].ts";
import * as $index from "./routes/index.tsx";
import * as $AocRunner from "./islands/AocRunner.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/aoc/[day]/[phase].ts": $api_aoc_day_phase_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AocRunner.tsx": $AocRunner,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
